### ISSUE TITLE
How to install plugins and themes?

### ISSUE THREAD

**Issue by huydhoang** [tibor-kocsis/octobercms-heroku#2]
Hi, I'm new to OctoberCMS. I found this tutorial today and it's so awesome! Thank you for sharing!
However, I haven't figured out how to install themes and plugins. I guess it would involve editing composer.json but I'm not quite sure how.
Could you please give me an instruction?

**Comment by huydhoang** [comment]
Think I found an answer here
https://stackoverflow.com/questions/43869868/plugin-management-and-versioning-in-octobercms
Will try and report back.

**Comment by tibor-kocsis** [comment]
My guess is you should install plugins and themes locally, then add under version control and push to heroku master. If you install octobercms plugins through the backend in the heroku environment, it will be deleted due the heroku ephemeral file system.

**Comment by huydhoang** [comment]
As I played with it, there're actually 3 ways to install plugins and themes. 

1. If they are available on packagist.org, you can add them under **require** in composer.json and run
`composer update`
Composer will take care of installing locally. Then do
`git push heroku master`

2. Not all plugins and themes are available on packagist. If the one you need is not there, you can to go to the public git repo of it (from october cms plugin/theme page). Clone and copy it manually to the git repo of octobercms on your local machine before pushing to heroku.

3. Alternatively, you can install octobercms locally with XAMPP, search and install plugin/theme in the local installation and copy theme over to your git repo to be pushed to heroku.
